// UI Constants for VibeTunnel

export const BREAKPOINTS = {
  MOBILE: 768,
  TABLET: 1024,
  DESKTOP: 1280,
} as const;

export const SIDEBAR = {
  DEFAULT_WIDTH: 320,
  MIN_WIDTH: 240,
  MAX_WIDTH: 600,
  MOBILE_RIGHT_MARGIN: 80,
} as const;

export const TRANSITIONS = {
  SIDEBAR: 200,
  MOBILE_SLIDE: 200,
  RESIZE_HANDLE: 200,
} as const;

export const Z_INDEX = {
  // Base UI elements
  TERMINAL_OVERLAY: 10,
  MOBILE_OVERLAY: 20,
  SIDEBAR_MOBILE: 30,
  WIDTH_SELECTOR_DROPDOWN: 50,

  // Modal and overlays
  MODAL_BACKDROP: 50,
  FILE_PICKER: 50,
  SESSION_EXITED_OVERLAY: 100,

  // File browser (needs to be above session create modal)
  FILE_BROWSER: 1100,

  // Other UI elements
  LOG_BUTTON: 20,
  CTRL_ALPHA_OVERLAY: 50,
  MOBILE_INPUT_OVERLAY: 40,
  SESSION_LIST_BOTTOM_BAR: 10,
} as const;

export const TERMINAL = {
  MIN_HEIGHT: 200,
  DEFAULT_VISIBLE_ROWS: 24,
  RESIZE_DEBOUNCE: 100,
} as const;

export const TIMING = {
  AUTO_REFRESH_INTERVAL: 1000,
  SESSION_SEARCH_DELAY: 500,
  KILL_ALL_ANIMATION_DELAY: 500,
  ERROR_MESSAGE_TIMEOUT: 5000,
  SUCCESS_MESSAGE_TIMEOUT: 5000,
  KILL_ALL_BUTTON_DISABLE_DURATION: 2000,
} as const;
