name: Tests

on:
  workflow_dispatch:
    inputs:
      test-type:
        description: 'Test type to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - unit
          - integration
          - e2e
      debug:
        description: 'Enable debug logging'
        required: false
        default: false
        type: boolean

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      DEBUG: ${{ inputs.debug && '*' || '' }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with:
          version: 9
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build native modules
        run: pnpm run build:native
        
      - name: Build application
        if: inputs.test-type == 'e2e' || inputs.test-type == 'all'
        run: pnpm run build
        
      - name: Install Playwright
        if: inputs.test-type == 'e2e' || inputs.test-type == 'all'
        run: pnpm exec playwright install --with-deps chromium
        
      - name: Run unit tests
        if: inputs.test-type == 'unit' || inputs.test-type == 'all'
        run: |
          echo "Running client unit tests..."
          pnpm run test:client:coverage || true
          echo "Running server unit tests..."
          pnpm run test:server:coverage || true
          
      - name: Run integration tests
        if: inputs.test-type == 'integration' || inputs.test-type == 'all'
        run: pnpm run test:integration || true
        
      - name: Run E2E tests
        if: inputs.test-type == 'e2e' || inputs.test-type == 'all'
        run: pnpm run test:e2e || true
        
      - name: Generate test report
        if: always()
        run: |
          echo "## Test Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Test type: ${{ inputs.test-type }}" >> $GITHUB_STEP_SUMMARY
          echo "Debug mode: ${{ inputs.debug }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -d coverage ]; then
            echo "### Coverage Reports" >> $GITHUB_STEP_SUMMARY
            find coverage -name "coverage-summary.json" -exec echo "Found: {}" \; >> $GITHUB_STEP_SUMMARY
          fi
          
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ inputs.test-type }}
          path: |
            coverage/
            test-results/
            playwright-report/
          retention-days: 7