name: Build Tauri App

on:
  push:
    branches: [ main, tauri-up ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            target: 'x86_64-apple-darwin'
          - platform: 'macos-latest'
            target: 'aarch64-apple-darwin'
          - platform: 'ubuntu-22.04'
            target: 'x86_64-unknown-linux-gnu'
          - platform: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: web/pnpm-lock.yaml

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python setuptools
      run: pip install setuptools

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './tauri/src-tauri -> target'

    - name: Install dependencies (Ubuntu)
      if: matrix.platform == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libpam0g-dev gcc-x86-64-linux-gnu

    - name: Install dependencies (Windows)
      if: matrix.platform == 'windows-latest'
      run: |
        choco install llvm -y

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install web dependencies
      working-directory: ./web
      run: |
        # Install dependencies (without frozen lockfile due to config differences)
        pnpm install
        # Rebuild native modules for the target platform
        pnpm rebuild

    - name: Build web assets
      working-directory: ./web
      run: pnpm run build

    - name: Cache tauri-cli
      id: cache-tauri
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/cargo-tauri
        key: ${{ runner.os }}-tauri-cli-2.0

    - name: Install tauri-cli
      if: steps.cache-tauri.outputs.cache-hit != 'true'
      run: cargo install tauri-cli --version "^2.0.0" --locked

    - name: Build Tauri app
      working-directory: ./tauri/src-tauri
      run: cargo tauri build --target ${{ matrix.target }} --ci

    - name: Upload artifacts (macOS)
      if: matrix.platform == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: vibetunnel-${{ matrix.target }}
        path: |
          tauri/src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg
          tauri/src-tauri/target/${{ matrix.target }}/release/bundle/macos/*.app
        if-no-files-found: error

    - name: Upload artifacts (Linux)
      if: matrix.platform == 'ubuntu-22.04'
      uses: actions/upload-artifact@v4
      with:
        name: vibetunnel-${{ matrix.target }}
        path: |
          tauri/src-tauri/target/${{ matrix.target }}/release/bundle/deb/*.deb
          tauri/src-tauri/target/${{ matrix.target }}/release/bundle/appimage/*.AppImage
        if-no-files-found: error

    - name: Upload artifacts (Windows)
      if: matrix.platform == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: vibetunnel-${{ matrix.target }}
        path: |
          tauri/src-tauri/target/${{ matrix.target }}/release/bundle/msi/*.msi
          tauri/src-tauri/target/${{ matrix.target }}/release/bundle/nsis/*.exe
        if-no-files-found: error