name: Node.js CI

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  lint:
    name: Lint TypeScript/JavaScript Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install dependencies
      working-directory: web
      run: npm ci

    - name: Check formatting with Biome
      id: biome-format
      working-directory: web
      continue-on-error: true
      run: |
        npm run format:check 2>&1 | tee biome-format-output.txt
        echo "result=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT

    - name: Run Biome linting
      id: biome-lint
      working-directory: web
      continue-on-error: true
      run: |
        npm run lint 2>&1 | tee biome-lint-output.txt
        echo "result=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT

    - name: Read Biome Format Output
      if: always()
      id: biome-format-output
      working-directory: web
      run: |
        if [ -f biome-format-output.txt ]; then
          echo 'content<<EOF' >> $GITHUB_OUTPUT
          cat biome-format-output.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        else
          echo "content=No output" >> $GITHUB_OUTPUT
        fi

    - name: Read Biome Lint Output
      if: always()
      id: biome-lint-output
      working-directory: web
      run: |
        if [ -f biome-lint-output.txt ]; then
          echo 'content<<EOF' >> $GITHUB_OUTPUT
          cat biome-lint-output.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        else
          echo "content=No output" >> $GITHUB_OUTPUT
        fi

    - name: Report Biome Format Results
      if: always()
      uses: ./.github/actions/lint-reporter
      with:
        title: 'Node.js Biome Formatting'
        lint-result: ${{ steps.biome-format.outputs.result == '0' && 'success' || 'failure' }}
        lint-output: ${{ steps.biome-format-output.outputs.content }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Report Biome Lint Results
      if: always()
      uses: ./.github/actions/lint-reporter
      with:
        title: 'Node.js Biome Linting'
        lint-result: ${{ steps.biome-lint.outputs.result == '0' && 'success' || 'failure' }}
        lint-output: ${{ steps.biome-lint-output.outputs.content }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install dependencies
      working-directory: web
      run: npm ci

    - name: Build frontend and backend
      working-directory: web
      run: npm run build:ci

    - name: Run tests
      working-directory: web
      run: npm run test:ci
      env:
        CI: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: node-build-artifacts
        path: |
          web/dist/
          web/public/bundle/

  type-check:
    name: TypeScript Type Checking
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install dependencies
      working-directory: web
      run: npm ci

    - name: Check TypeScript types
      working-directory: web
      run: npm run typecheck

  audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Run npm audit
      working-directory: web
      run: npm audit --audit-level=moderate || true
      # || true to not fail the build on vulnerabilities, but still report them